# Generated by Django 3.0 on 2020-01-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('facultyid', models.IntegerField(primary_key=True, serialize=False)),
                ('facultyname', models.CharField(blank=True, max_length=20, null=True)),
                ('designation', models.CharField(max_length=20)),
                ('joiningdate', models.DateField()),
                ('qualification', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('batchincharge', models.CharField(blank=True, max_length=20, null=True)),
                ('blood', models.CharField(max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
                ('mobileno', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
