# Generated by Django 3.0 on 2020-01-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='cnfrmpassword',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
