# Generated by Django 3.0 on 2020-01-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_auto_20200114_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('admissionno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('rollno', models.IntegerField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('batch', models.CharField(blank=True, max_length=20, null=True)),
                ('joiningdate', models.CharField(max_length=20)),
                ('mobileno', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('batchincharge', models.CharField(blank=True, max_length=20, null=True)),
                ('blood', models.CharField(max_length=10)),
                ('dob', models.DateField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
