# Generated by Django 3.0 on 2020-01-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentleave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('rollno', models.IntegerField()),
                ('leavefrom', models.CharField(blank=True, max_length=50, null=True)),
                ('leaveto', models.CharField(blank=True, max_length=50, null=True)),
                ('leavetype', models.CharField(blank=True, max_length=30, null=True)),
                ('reason', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='joiningdate',
            new_name='admissiondate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='batchincharge',
        ),
    ]
